name: test oceanbase-ce

on:
  push:
    branches: [ '**' ]
  pull_request:
    paths:
      - '.github/workflows/**-oceanbase-ce.yml'
      - 'oceanbase-ce/**'
      - 'test/**'

concurrency:
  group: test-oceanbase-ce-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: ./oceanbase-ce/docker_build.sh

      - name: Export Docker image
        run: docker save -o oceanbase-ce.tar oceanbase-ce

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: oceanbase-ce
          path: oceanbase-ce.tar

  test-slim:
    uses: ./.github/workflows/java-test-oceanbase-ce.yml
    with:
      cache_key: oceanbase-ce
      image_file: oceanbase-ce.tar
      mode: slim
      port: 1234
      sys_password: ''
      test_tenant: test
      test_password: 123456
      server_ip: 127.0.0.1
      rs_list: 127.0.0.1:2882:2881
      init_sql: "ALTER USER root IDENTIFIED BY '123456'"
