name: test oceanbase-ce

on:
  push:
    branches: [ main ]
  pull_request:
    paths:
      - '.github/workflows/**-oceanbase-ce.yml'
      - 'oceanbase-ce/**'
      - 'test/**'

jobs:
  build:
    uses: ./.github/workflows/build-oceanbase-ce.yml
    with:
      cache_key: oceanbase-ce
      image_file: oceanbase-ce.tar

  test-slim:
    needs: build
    uses: ./.github/workflows/java-test-oceanbase-ce.yml
    with:
      cache_key: oceanbase-ce
      image_file: oceanbase-ce.tar
      mode: slim
      port: 1234
      sys_password: ''
      test_tenant: test
      test_password: 123456
      server_ip: 127.0.0.1
      rs_list: 127.0.0.1:2882:2881
      init_sql: "ALTER USER root IDENTIFIED BY '123456'"
